[2024-09-08T21:09:08.285-0300] {processor.py:186} INFO - Started process (PID=10759) to work on /home/kasten/airflow/dags/spotify_dag copy.py
[2024-09-08T21:09:08.285-0300] {processor.py:914} INFO - Processing file /home/kasten/airflow/dags/spotify_dag copy.py for tasks to queue
[2024-09-08T21:09:08.288-0300] {logging_mixin.py:190} INFO - [2024-09-08T21:09:08.287-0300] {dagbag.py:587} INFO - Filling up the DagBag from /home/kasten/airflow/dags/spotify_dag copy.py
[2024-09-08T21:09:08.293-0300] {processor.py:925} INFO - DAG(s) 'spotify_dag' retrieved from /home/kasten/airflow/dags/spotify_dag copy.py
[2024-09-08T21:09:08.364-0300] {logging_mixin.py:190} INFO - [2024-09-08T21:09:08.364-0300] {dag.py:3229} INFO - Sync 1 DAGs
[2024-09-08T21:09:08.372-0300] {logging_mixin.py:190} INFO - [2024-09-08T21:09:08.371-0300] {dag.py:3252} INFO - Creating ORM DAG for spotify_dag
[2024-09-08T21:09:08.378-0300] {logging_mixin.py:190} INFO - [2024-09-08T21:09:08.378-0300] {dag.py:4156} INFO - Setting next_dagrun for spotify_dag to 2024-09-08 21:30:00+00:00, run_after=2024-09-09 21:30:00+00:00
[2024-09-08T21:09:08.843-0300] {logging_mixin.py:190} INFO - [2024-09-08T21:09:08.842-0300] {dagbag.py:697} ERROR - Failed to write serialized DAG: /home/kasten/airflow/dags/spotify_dag copy.py
Traceback (most recent call last):
  File "/home/kasten/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 685, in _serialize_dag_capturing_errors
    dag_was_updated = SerializedDagModel.write_dag(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kasten/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 94, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/kasten/.local/lib/python3.12/site-packages/airflow/models/serialized_dag.py", line 160, in write_dag
    if session.scalar(
       ^^^^^^^^^^^^^^^
  File "/home/kasten/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1747, in scalar
    return self.execute(
           ^^^^^^^^^^^^^
  File "/home/kasten/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kasten/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kasten/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 724, in _connection_for_bind
    self._assert_active()
  File "/home/kasten/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 604, in _assert_active
    raise sa_exc.PendingRollbackError(
sqlalchemy.exc.PendingRollbackError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (sqlite3.IntegrityError) UNIQUE constraint failed: dag_tag.name, dag_tag.dag_id
[SQL: INSERT INTO dag_tag (name, dag_id) VALUES (?, ?)]
[parameters: (('spotify', 'spotify_dag'), ('homologation', 'spotify_dag'), ('test_dag', 'spotify_dag'))]
(Background on this error at: https://sqlalche.me/e/14/gkpj) (Background on this error at: https://sqlalche.me/e/14/7s2a)
[2024-09-08T21:09:08.844-0300] {logging_mixin.py:190} INFO - [2024-09-08T21:09:08.844-0300] {dag.py:3229} INFO - Sync 1 DAGs
[2024-09-08T21:09:08.844-0300] {processor.py:211} ERROR - Got an exception! Propagating...
Traceback (most recent call last):
  File "/home/kasten/.local/lib/python3.12/site-packages/airflow/dag_processing/processor.py", line 207, in _run_file_processor
    _handle_dag_file_processing()
  File "/home/kasten/.local/lib/python3.12/site-packages/airflow/dag_processing/processor.py", line 188, in _handle_dag_file_processing
    result: tuple[int, int, int] = dag_file_processor.process_file(
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kasten/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kasten/.local/lib/python3.12/site-packages/airflow/dag_processing/processor.py", line 942, in process_file
    serialize_errors = DagFileProcessor.save_dag_to_db(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kasten/.local/lib/python3.12/site-packages/airflow/api_internal/internal_api_call.py", line 139, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/kasten/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kasten/.local/lib/python3.12/site-packages/airflow/dag_processing/processor.py", line 982, in save_dag_to_db
    import_errors = DagBag._sync_to_db(dags=dags, processor_subdir=dag_directory, session=session)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kasten/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 94, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/kasten/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 707, in _sync_to_db
    for attempt in run_with_db_retries(logger=log):
  File "/home/kasten/.local/lib/python3.12/site-packages/tenacity/__init__.py", line 443, in __iter__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kasten/.local/lib/python3.12/site-packages/tenacity/__init__.py", line 376, in iter
    result = action(retry_state)
             ^^^^^^^^^^^^^^^^^^^
  File "/home/kasten/.local/lib/python3.12/site-packages/tenacity/__init__.py", line 398, in <lambda>
    self._add_action_func(lambda rs: rs.outcome.result())
                                     ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/home/kasten/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 723, in _sync_to_db
    DAG.bulk_write_to_db(dags.values(), processor_subdir=processor_subdir, session=session)
  File "/home/kasten/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 94, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/kasten/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 3242, in bulk_write_to_db
    orm_dags: list[DagModel] = session.scalars(query).unique().all()
                               ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kasten/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1778, in scalars
    return self.execute(
           ^^^^^^^^^^^^^
  File "/home/kasten/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kasten/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kasten/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 724, in _connection_for_bind
    self._assert_active()
  File "/home/kasten/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 604, in _assert_active
    raise sa_exc.PendingRollbackError(
sqlalchemy.exc.PendingRollbackError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (sqlite3.IntegrityError) UNIQUE constraint failed: dag_tag.name, dag_tag.dag_id
[SQL: INSERT INTO dag_tag (name, dag_id) VALUES (?, ?)]
[parameters: (('spotify', 'spotify_dag'), ('homologation', 'spotify_dag'), ('test_dag', 'spotify_dag'))]
(Background on this error at: https://sqlalche.me/e/14/gkpj) (Background on this error at: https://sqlalche.me/e/14/7s2a)
[2024-09-08T21:09:25.343-0300] {processor.py:186} INFO - Started process (PID=10857) to work on /home/kasten/airflow/dags/spotify_dag copy.py
[2024-09-08T21:09:25.343-0300] {processor.py:914} INFO - Processing file /home/kasten/airflow/dags/spotify_dag copy.py for tasks to queue
[2024-09-08T21:09:25.345-0300] {logging_mixin.py:190} INFO - [2024-09-08T21:09:25.344-0300] {dagbag.py:587} INFO - Filling up the DagBag from /home/kasten/airflow/dags/spotify_dag copy.py
[2024-09-08T21:09:25.350-0300] {processor.py:925} INFO - DAG(s) 'spotify_dag_001' retrieved from /home/kasten/airflow/dags/spotify_dag copy.py
[2024-09-08T21:09:25.425-0300] {logging_mixin.py:190} INFO - [2024-09-08T21:09:25.425-0300] {override.py:1900} INFO - Created Permission View: can delete on DAG:spotify_dag_001
[2024-09-08T21:09:25.435-0300] {logging_mixin.py:190} INFO - [2024-09-08T21:09:25.435-0300] {override.py:1900} INFO - Created Permission View: can read on DAG:spotify_dag_001
[2024-09-08T21:09:25.444-0300] {logging_mixin.py:190} INFO - [2024-09-08T21:09:25.444-0300] {override.py:1900} INFO - Created Permission View: can edit on DAG:spotify_dag_001
[2024-09-08T21:09:25.458-0300] {logging_mixin.py:190} INFO - [2024-09-08T21:09:25.457-0300] {override.py:1900} INFO - Created Permission View: menu access on DAG Run:spotify_dag_001
[2024-09-08T21:09:25.466-0300] {logging_mixin.py:190} INFO - [2024-09-08T21:09:25.465-0300] {override.py:1900} INFO - Created Permission View: can delete on DAG Run:spotify_dag_001
[2024-09-08T21:09:25.474-0300] {logging_mixin.py:190} INFO - [2024-09-08T21:09:25.474-0300] {override.py:1900} INFO - Created Permission View: can read on DAG Run:spotify_dag_001
[2024-09-08T21:09:25.482-0300] {logging_mixin.py:190} INFO - [2024-09-08T21:09:25.482-0300] {override.py:1900} INFO - Created Permission View: can create on DAG Run:spotify_dag_001
[2024-09-08T21:09:25.482-0300] {logging_mixin.py:190} INFO - [2024-09-08T21:09:25.482-0300] {dag.py:3229} INFO - Sync 1 DAGs
[2024-09-08T21:09:25.490-0300] {logging_mixin.py:190} INFO - [2024-09-08T21:09:25.490-0300] {dag.py:3252} INFO - Creating ORM DAG for spotify_dag_001
[2024-09-08T21:09:25.496-0300] {logging_mixin.py:190} INFO - [2024-09-08T21:09:25.496-0300] {dag.py:4156} INFO - Setting next_dagrun for spotify_dag_001 to 2024-09-08 21:30:00+00:00, run_after=2024-09-09 21:30:00+00:00
[2024-09-08T21:09:25.512-0300] {processor.py:208} INFO - Processing /home/kasten/airflow/dags/spotify_dag copy.py took 0.173 seconds
[2024-09-08T21:09:55.765-0300] {processor.py:186} INFO - Started process (PID=10984) to work on /home/kasten/airflow/dags/spotify_dag copy.py
[2024-09-08T21:09:55.766-0300] {processor.py:914} INFO - Processing file /home/kasten/airflow/dags/spotify_dag copy.py for tasks to queue
[2024-09-08T21:09:55.767-0300] {logging_mixin.py:190} INFO - [2024-09-08T21:09:55.767-0300] {dagbag.py:587} INFO - Filling up the DagBag from /home/kasten/airflow/dags/spotify_dag copy.py
[2024-09-08T21:09:55.772-0300] {processor.py:925} INFO - DAG(s) 'spotify_dag_001' retrieved from /home/kasten/airflow/dags/spotify_dag copy.py
[2024-09-08T21:09:55.779-0300] {logging_mixin.py:190} INFO - [2024-09-08T21:09:55.779-0300] {dag.py:3229} INFO - Sync 1 DAGs
[2024-09-08T21:09:55.793-0300] {logging_mixin.py:190} INFO - [2024-09-08T21:09:55.793-0300] {dag.py:4156} INFO - Setting next_dagrun for spotify_dag_001 to 2024-09-08 21:30:00+00:00, run_after=2024-09-09 21:30:00+00:00
[2024-09-08T21:09:55.810-0300] {processor.py:208} INFO - Processing /home/kasten/airflow/dags/spotify_dag copy.py took 0.050 seconds
